config/routes.rb
Rails.application.routes.draw do
  resources :generos
  resources :autors
  resources :livros
root "livros#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/autor.rb
class Autor < ApplicationRecord
end

app/models/genero.rb
class Genero < ApplicationRecord
end

app/models/livro.rb
class Livro < ApplicationRecord
  belongs_to:autor
  belongs_to:genero
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController
  before_action :set_autor, only: %i[ show edit update destroy ]

  # GET /autors or /autors.json
  def index
    @autors = Autor.all
  end

  # GET /autors/1 or /autors/1.json
  def show
  end

  # GET /autors/new
  def new
    @autor = Autor.new
  end

  # GET /autors/1/edit
  def edit
  end

  # POST /autors or /autors.json
  def create
    @autor = Autor.new(autor_params)

    respond_to do |format|
      if @autor.save
        format.html { redirect_to autor_url(@autor), notice: "Autor was successfully created." }
        format.json { render :show, status: :created, location: @autor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autors/1 or /autors/1.json
  def update
    respond_to do |format|
      if @autor.update(autor_params)
        format.html { redirect_to autor_url(@autor), notice: "Autor was successfully updated." }
        format.json { render :show, status: :ok, location: @autor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @autor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autors/1 or /autors/1.json
  def destroy
    @autor.destroy

    respond_to do |format|
      format.html { redirect_to autors_url, notice: "Autor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_autor
      @autor = Autor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def autor_params
      params.require(:autor).permit(:nome)
    end
end

app/controllers/generos_controller.rb
class GenerosController < ApplicationController
  before_action :set_genero, only: %i[ show edit update destroy ]

  # GET /generos or /generos.json
  def index
    @generos = Genero.all
  end

  # GET /generos/1 or /generos/1.json
  def show
  end

  # GET /generos/new
  def new
    @genero = Genero.new
  end

  # GET /generos/1/edit
  def edit
  end

  # POST /generos or /generos.json
  def create
    @genero = Genero.new(genero_params)

    respond_to do |format|
      if @genero.save
        format.html { redirect_to genero_url(@genero), notice: "Genero was successfully created." }
        format.json { render :show, status: :created, location: @genero }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generos/1 or /generos/1.json
  def update
    respond_to do |format|
      if @genero.update(genero_params)
        format.html { redirect_to genero_url(@genero), notice: "Genero was successfully updated." }
        format.json { render :show, status: :ok, location: @genero }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generos/1 or /generos/1.json
  def destroy
    @genero.destroy

    respond_to do |format|
      format.html { redirect_to generos_url, notice: "Genero was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genero
      @genero = Genero.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def genero_params
      params.require(:genero).permit(:nome)
    end
end

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: %i[ show edit update destroy ]

  # GET /livros or /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1 or /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end

  # POST /livros or /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully created." }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1 or /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to livro_url(@livro), notice: "Livro was successfully updated." }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1 or /livros/1.json
  def destroy
    @livro.destroy

    respond_to do |format|
      format.html { redirect_to livros_url, notice: "Livro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def livro_params
      params.require(:livro).permit(:nome, :ano_de_publicacao, :edicao, :autor_id, :genero_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autors_helper.rb
module AutorsHelper
end

app/helpers/generos_helper.rb
module GenerosHelper
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/autors/_autor.html.erb
<div id="<%= dom_id autor %>" style="background: #cdbbbb; border: 30px solid pink; border-radius: 20px; padding: 15px; margin-right: 70em;margin: 0 auto; width: 40%;">
  <p>
    <strong>Nome do Autor:</strong>
    <%= autor.nome %>
  </p>

</div>

app/views/autors/_form.html.erb
<%= form_with(model: autor) do |form| %>
  <% if autor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(autor.errors.count, "error") %> prohibited this autor from being saved:</h2>

      <ul>
        <% autor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/autors/edit.html.erb
<h1 style="color: #8f244d; margin-left: 10em;">Editar Autor
  <i class="bi bi-pencil-square"></i></h1>
<div style="background: #cdbbbb; border: 30px solid pink; border-radius: 20px; padding: 15px; margin-right: 70em;margin: 0 auto; width: 40%;">
<%= render "form", autor: @autor %>
</div>
<br>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;">
  <%= link_to "Mostrar autor", @autor %> |
  <%= link_to "Voltar para autores", autors_path %>
</div>

    <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/autors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color: #8f244d; margin-left: 22em;">Autores 
  <i class="bi bi-person-video2"></i></h1>

<div id="autors">
  <% @autors.each do |autor| %>
    <%= render autor %>
    <p style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
      <%= link_to "Mostrar autor", autor %>
    </p>/</br>
  <% end %>
</div>

    <div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
<%= link_to "Novo autor", new_autor_path %>
    </div>

    
<style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/autors/new.html.erb
<h1 style="color: #8f244d; margin-left: 10em;">Novo Autor
  <i class="bi bi-journal-plus"></i></h1>

<%= render "form", autor: @autor %>

<br>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;">
  <%= link_to "Voltar para autores", autors_path %>
</div>


  <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/autors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @autor %>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;">
  <%= link_to "Editar autor", edit_autor_path(@autor) %> |
  <%= link_to "Voltar para autores", autors_path %>

  <%= button_to "Excluir autor", @autor, method: :delete %>
</div>


    <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/generos/_form.html.erb
<%= form_with(model: genero) do |form| %>
  <% if genero.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genero.errors.count, "error") %> prohibited this genero from being saved:</h2>

      <ul>
        <% genero.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/generos/_genero.html.erb
<div id="<%= dom_id genero %>" style="background: #cdbbbb; border: 30px solid pink; border-radius: 20px; padding: 15px; margin-right: 70em; margin: 0 auto; width: 40%;">
  <p>
    <strong>Gênero do Livro:</strong>
    <%= genero.nome %>
  </p>

</div>

app/views/generos/edit.html.erb
<h1 style="color: #8f244d; margin-left: 10em;">Editar Gênero
  <i class="bi bi-pencil-square"></i></h1>

<%= render "form", genero: @genero %>

<br>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
  <%= link_to "Mostrar gênero", @genero %> |
  <%= link_to "Voltar para gêneros", generos_path %>
</div>


      <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/generos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color: #8f244d; margin-left: 20em;">Gêneros Literários
  <i class="bi bi-journals"></i></h1>

<div id="generos">
  <% @generos.each do |genero| %>
    <%= render genero %>
    <p style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
      <%= link_to "Mostrar gênero", genero %>
    </p><br>
  <% end %>
</div>

    <div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
<%= link_to "Novo gênero", new_genero_path %>
    </div>

    <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/generos/new.html.erb
<h1 style="color: #8f244d; margin-left: 2em;">Novo Gênero
  <i class="bi bi-journal-plus"></i></h1>

<%= render "form", genero: @genero %>

<br>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
  <%= link_to "Voltar para gêneros", generos_path %>
</div>

    <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/generos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @genero %>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
  <%= link_to "Editar gênero", edit_genero_path(@genero) %> |
  <%= link_to "Voltar para gêneros", generos_path %>

  <%= button_to "Excluir gênero", @genero, method: :delete %>
</div>


      <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LIVR'ART</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <!-- BOOSTRAP NAV -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <!-- CDN ICON BOOTSTRAP-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

       <style>
        body{
          background: linear-gradient(to right, #939396, #ffd2bf);
        }
          .navbar {
  background-color:  #98173d;
           color: #b9f1d6;
}
         </style>

    
      
  <body>


    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-md ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" style="color: #d2fdfe;">LIVR'ART </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item" >
          <a class="nav-link active" aria-current="page" href="https://spacerails7.thayaneferreir2.repl.co" style="color: #d2fdfe;">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://spacerails7.thayaneferreir2.repl.co/autors" style="color: #d2fdfe;">Autores</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://spacerails7.thayaneferreir2.repl.co/generos" style="color: #d2fdfe;">Gênero Literário</a>
        </li>
        
      </ul>
    </div>
  </div>
</nav>





    
    
    <%= yield %>
  </body>
     
</html>

app/views/livros/_form.html.erb
<%= form_with(model: livro) do |form| %>
  <% if livro.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
        <% livro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= form.label :autor %>
    <%= collection_select(:livro, :autor_id,Autor.all ,:id, :nome)%>
  </div>

  <div class="field">
    <%= form.label :genero %>
    <%= collection_select(:livro, :genero_id,Genero.all ,:id, :nome)%>
  </div>
    
  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano_de_publicacao, style: "display: block" %>
    <%= form.number_field :ano_de_publicacao %>
  </div>

  <div>
    <%= form.label :edicao, style: "display: block" %>
    <%= form.text_field :edicao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/livros/_livro.html.erb
<div id="<%= dom_id livro %>" style="background: #cdbbbb; border: 30px solid pink; border-radius: 20px; padding: 15px; margin-right: 50em; margin: 0 auto; width: 40%;">
  
  <p>
    <strong>Nome:</strong>
    <%= livro.nome %>
  </p>

<p>
<strong>Autor:</strong>
<%= livro.autor.nome %>
</p>

<p>
<strong>Gênero:</strong>
<%= livro.genero.nome %>
</p>

  <p>
    <strong>Ano de publicação:</strong>
    <%= livro.ano_de_publicacao %>
  </p>

  <p>
    <strong>Edição:</strong>
    <%= livro.edicao %>
  </p>

</div>

app/views/livros/edit.html.erb
<h1 style="color: #8f244d; margin-left: 10em;">Editar Livro
  <i class="bi bi-pencil-square"></i></h1>

<%= render "form", livro: @livro %>

<br>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
  <%= link_to "Mostrar Livro", @livro %> |
  <%= link_to "Voltar para Livros", livros_path %>
</div>


    <style>
  a {
    text-decoration: none; 
     font-family: cursive;
  }
</style>

app/views/livros/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="color: #8f244d; margin-left: 22em; ">LIVROS
<i class="bi bi-journal-bookmark"></i></h1>


<div id="livros">
  <% @livros.each do |livro| %>
    <%= render livro %>
      <%= livro.autor.nome %>
      <%= livro.genero.nome %>
    <p style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
      <%= link_to "Mostrar livro", livro %>
    </p></br>
  <% end %>
</div>

    <div id="bt" style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;" >
      <%= link_to "Adicionar novo livro", new_livro_path %>
    </div>

<style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>

app/views/livros/new.html.erb
<h1 style="color: #8f244d; margin-left: 10em;">Novo Livro
  <i class="bi bi-journal-plus"></i></h1>

<%= render "form", livro: @livro %>

<br>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 70em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
  <%= link_to "Voltar para livros", livros_path %>
</div>

  <style>
  a {
    text-decoration: none; 
     font-family: cursive;
  }
</style>

app/views/livros/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @livro %>

<div style="border: 2px solid #81d7cd; border-radius: 20px; padding: 0.5em; margin-right: 50em; text-align: center; background-color:#c0ebe6;margin: 0 auto; width: 40%;">
  <%= link_to "Editar Livro", edit_livro_path(@livro) %> |
  <%= link_to "Voltar para Livros", livros_path %>

  <%= button_to "Excluir Livro", @livro, method: :delete %>
</div>

    <style>
  a {
    text-decoration: none; 
    font-family: cursive;
  }
</style>